# frozen_string_literal: true

module Mailkube
  # Typed models for inbound webhook payloads.
  module Events
    # A typed lens over one decoded JSON object from a webhook payload.
    #
    # Every other model in this gem is a `Data.define`, whose members are fixed — which is exactly
    # why none of them can be used here. The contract **inverts** the response-model rule for
    # events: unknown fields are *preserved*, not dropped, at every nesting depth, so a receiver
    # that logs or forwards an event keeps fields this release predates. A `Data` drops them at
    # parse time and offers no way to ask it not to.
    #
    # So the storage is inverted rather than fought. The decoded hash **is** this object's state,
    # and a subclass adds one-line readers naming the fields this release knows. Nothing is copied,
    # so nothing can be lost, and {#raw} round-trips to exactly what the server sent. Nested blocks
    # are built on read, so a receiver that only touches `data.email_id` never allocates the rest.
    #
    # Readers are written out as plain `def`s rather than generated by a macro: Steep's
    # `UndeclaredMethodDefinition` gate reads what is in `lib/`, and a generated reader is a method
    # no signature can be matched against.
    class Node
      # @return [Hash{String => Object}] the verbatim decoded object, unknown fields included.
      attr_reader :raw

      # @param raw [Hash{String => Object}] the decoded JSON object for this block.
      def initialize(raw)
        @raw = raw
        freeze
      end

      # Read any field by its wire name, whether or not this release models it.
      #
      # This is the forward-compatibility escape hatch the contract asks for: a field the platform
      # adds after this gem ships is reachable here on the day it appears.
      #
      # @param key [String] the wire field name.
      # @return [Object, nil] the value, or nil when the server did not send it.
      def [](key) = @raw[key]

      # @return [Hash{String => Object}] the verbatim decoded object, for logging or forwarding.
      def to_h = @raw

      # @param other [Object] the object to compare with.
      # @return [Boolean] true when both are the same class over the same payload.
      def ==(other) = other.instance_of?(self.class) && other.raw == @raw
      alias eql? ==

      # @return [Integer] a hash consistent with {#==}.
      def hash = [self.class, @raw].hash

      private

      # Build a nested block, tolerating a server that omitted the key entirely.
      #
      # @param type [Class] the {Node} subclass modelling the nested object.
      # @param key [String] the wire field holding it.
      # @return [Node] the nested block.
      def block(type, key) = type.new(self[key] || {})
    end
  end
end
